'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRM_HERB_TABEAN_ADD_DETAIL

    '''<summary>
    '''NAME_TB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_TB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_PLACE_TB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_PLACE_TB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''data_show3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data_show3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_agent99 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_agent99 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TXT_SEARCH_TN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_SEARCH_TN As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_SEARCH_TN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SEARCH_TN As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_person_age control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_person_age As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_NATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_NATION As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''data_show1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data_show1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''data_show2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents data_show2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_nation_person control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_nation_person As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_TYPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_TYPE_NAME As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_TYPE_SUB_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_TYPE_SUB_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_CATEGORY_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_CATEGORY_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lab_category_out_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lab_category_out_id As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DD_CATEGORY_OUT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_CATEGORY_OUT_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''foreign control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents foreign As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_search As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_search_ida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_search_ida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HiddenField1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HiddenField1 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''btn_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadGrid2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid2 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGrid3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid3 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''txt_address control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_address As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_address_ida control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_address_ida As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_THAI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_THAI As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_OTHER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_OTHER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_STYPE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_STYPE_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''SIZE_PACK control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIZE_PACK As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_PCAK_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_PCAK_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_PCAK_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_size_pack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_size_pack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''NATURE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NATURE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''STAFF_KEY_SET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STAFF_KEY_SET As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NO_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_ID As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_MANUFAC_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_MANUFAC_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_add_muc_add control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_muc_add As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''DD_SYNDROME_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_SYNDROME_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''PROPERTIES control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PROPERTIES As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SIZE_USE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SIZE_USE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''HOW_USE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HOW_USE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_EATTING_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_EATTING_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''R_EATTING_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_EATTING_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DD_EATING_CONDITION_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_EATING_CONDITION_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''R_EATING_CONDITION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_EATING_CONDITION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''EATING_CONDITION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EATING_CONDITION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_STORAGE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_STORAGE_ID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''TREATMENT_AGE_YEAR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TREATMENT_AGE_YEAR As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''div_hide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_hide As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TREATMENT_AGE_MONTH_SUB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TREATMENT_AGE_MONTH_SUB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''div_hide2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_hide2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''R_CONTRAINDICATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CONTRAINDICATION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''R_CONTRAINDICATION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CONTRAINDICATION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CONTRAINDICATION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CONTRAINDICATION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_WARNING_TYPE_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_WARNING_TYPE_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''WARNING_TYPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WARNING_TYPE_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_WARNING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_WARNING As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''DD_WARNING control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_WARNING As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_WARNING_SUB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_WARNING_SUB As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''R_WARNING_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_WARNING_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''WARNING_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents WARNING_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_CAUTION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CAUTION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''R_CAUTION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_CAUTION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CAUTION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CAUTION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''R_ADV_REACTIVETION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_ADV_REACTIVETION As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''R_ADV_REACTIVETION_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents R_ADV_REACTIVETION_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ADV_REACTIVETION_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ADV_REACTIVETION_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''SALE_CHANNEL_SET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SALE_CHANNEL_SET As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DD_SALE_CHANNEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_SALE_CHANNEL As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RBL_CHK_PRODUCER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RBL_CHK_PRODUCER As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''DIV_PRODUCER_SHOW1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_PRODUCER_SHOW1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''DIV_PRODUCER_SHOW2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_PRODUCER_SHOW2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TXT_LCNNO_SEARCH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_LCNNO_SEARCH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_SEARCH_PRODUCER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SEARCH_PRODUCER As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DIV_LCNNO_SHOW_GRID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_LCNNO_SHOW_GRID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadGrid_LCNNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid_LCNNO As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''btn_select control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_select As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DIV_PRODUCER_SHOW_GRID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_PRODUCER_SHOW_GRID As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadGrid_PRODUCER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid_PRODUCER As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''btn_save_work_type control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save_work_type As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RECIPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RECIPE_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DDL_RECIPE_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDL_RECIPE_NAME As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''STAFF_HIDE_SET control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents STAFF_HIDE_SET As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''UC_ATTACH1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH1 As Global.FDA_DRUG_HERB.UC_ATTACH

    '''<summary>
    '''UC_ATTACH2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH2 As Global.FDA_DRUG_HERB.UC_ATTACH

    '''<summary>
    '''UC_officer_che control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_officer_che As Global.FDA_DRUG_HERB.UC_officer_che

    '''<summary>
    '''btn_save control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_save As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button
End Class
