'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class FRM_HERB_TABEAN_ADD_DETAIL_CHKACC

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''ACCEPT_FORMULA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ACCEPT_FORMULA As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''ACCEPT_FORMULA_TEXT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ACCEPT_FORMULA_TEXT As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ACCEPT_FORMULA_NOTE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ACCEPT_FORMULA_NOTE As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_summit2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_summit2 As Global.System.Web.UI.WebControls.Button
End Class
