'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_TABEAN_EDIT_SELECT_LIST

    '''<summary>
    '''P1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''P3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents P3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_rgtno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_rgtno As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CB_NAME_PRODUCT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_NAME_PRODUCT_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''DV_NAME_SL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DV_NAME_SL As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CB_NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_NAME_ENG As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_NAME_OTHER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_NAME_OTHER As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_NAME_EXPORT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_NAME_EXPORT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_NAME_LOCATION_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_NAME_LOCATION_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Div_NAME_LOCATION control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_NAME_LOCATION As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_PRODUCT_RECIPE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_PRODUCT_RECIPE_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Div_SubProductRecipe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_SubProductRecipe As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBox_SubRecipe1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubRecipe1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBox_SubRecipe1_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubRecipe1_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_SubRecipe1_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubRecipe1_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_SubRecipe2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubRecipe2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Div3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBox_SubRecipe2_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubRecipe2_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_PRODUCTION_PROCESS_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_PRODUCTION_PROCESS_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_PROPERTIES_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_PROPERTIES_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_SIZE_USE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_SIZE_USE_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_PREPARE_EAT_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_PREPARE_EAT_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_EAT_CONDITION_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_EAT_CONDITION_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_STORAGE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_STORAGE_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_CONTAINER_PACKING_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_CONTAINER_PACKING_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_QUALITY_CONTROL_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_QUALITY_CONTROL_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''Div_SubQuality_Control control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div_SubQuality_Control As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBox_SubQuality1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubQuality1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_SubQuality2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_SubQuality2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_CER_LCN_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_CER_LCN_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_ETIQUETQ_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_ETIQUETQ_ID As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB_CHANNEL_SALE_ID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_CHANNEL_SALE_ID As Global.System.Web.UI.WebControls.CheckBox
End Class
