'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_ANALYZE_DETAIL

    '''<summary>
    '''Txt_Write_At control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Write_At As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Write_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Write_Date As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_position As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdl_behalf_in control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_behalf_in As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txt_lcn_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcn_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lcnno_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcnno_new As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ampher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ampher As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_changwhat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_changwhat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_drug_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_drug_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_PCAK_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_PCAK_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_PCAK_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_size_pack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_size_pack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid
End Class
