'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_EXHIBITION_DETAIL

    '''<summary>
    '''Txt_Write_At control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_Write_At As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RDP_Write_Date control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDP_Write_Date As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txt_NAME control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_NAME As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_position control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_position As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdl_behalf_in control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_behalf_in As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''div_behalf_in_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_behalf_in_other As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_behalf_in control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_behalf_in As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txt_other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lcn_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcn_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_lcnno_new control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcnno_new As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Panel_lcnno control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_lcnno As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txt_lcnno_SEACH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lcnno_SEACH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''BTN_SEARCH_LCNNO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BTN_SEARCH_LCNNO As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Panel_lcnno_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel_lcnno_search As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''txt_house_no control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_house_no As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btn_search control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_search As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txt_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ampher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ampher As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_changwhat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_changwhat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_longtitute control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_longtitute As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_latituie control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_latituie As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdl_process_exh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_process_exh As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''txt_drug_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_drug_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_num control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_num As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_exhibition control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_exhibition As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''RDP_date_Start control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDP_date_Start As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''RDP_date_End control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RDP_date_End As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txt_lo_exh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_lo_exh As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UC_EXH_DETAIL_CAS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_EXH_DETAIL_CAS As Global.FDA_DRUG_HERB.UC_EXH_DETAIL_CAS

    '''<summary>
    '''DD_PCAK_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_PCAK_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_2 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''DD_PCAK_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_PCAK_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''NO_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NO_3 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''DD_UNIT_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DD_UNIT_3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btn_size_pack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_size_pack As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid
End Class
