'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class UC_EDIT_NAME_PRODUCT

    '''<summary>
    '''ID1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ID1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''cb_sub_menu_1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_sub_menu_1 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NAME_ENG control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_ENG As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_ENG_NEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_ENG_NEW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_sub_menu_2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_sub_menu_2 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NAME_OTHER control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_OTHER As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''NAME_OTHER_NEW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NAME_OTHER_NEW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_sub_menu_3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_sub_menu_3 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txt_NameEXP_Eng control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_NameEXP_Eng As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txt_NameEXP_Eng_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_NameEXP_Eng_New As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cb_sub_menu_4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cb_sub_menu_4 As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CB4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''Txt_NameEXP_Other control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_NameEXP_Other As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''Txt_NameEXP_Other_New control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Txt_NameEXP_Other_New As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CB_All control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CB_All As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
