'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace SW_HERB_PAYMENT
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="SW_LCN_EDIT_PAYMENTSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SW_LCN_EDIT_PAYMENT
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HERB_PAYMENTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private INSERT_HERB_PAYMENT_CENTER_L44OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FDA_DRUG_HERB.My.MySettings.Default.FDA_DRUG_HERB_SW_HERB_PAYMENT_SW_LCN_EDIT_PAYMENT
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HERB_PAYMENTCompleted As HERB_PAYMENTCompletedEventHandler
        
        '''<remarks/>
        Public Event INSERT_HERB_PAYMENT_CENTER_L44Completed As INSERT_HERB_PAYMENT_CENTER_L44CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_PAYMENT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub HERB_PAYMENT(ByVal _IDA As Integer, ByVal _PROCESS_ID As String, ByVal _REF01 As String, ByVal _REF02 As String)
            Me.Invoke("HERB_PAYMENT", New Object() {_IDA, _PROCESS_ID, _REF01, _REF02})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_PAYMENTAsync(ByVal _IDA As Integer, ByVal _PROCESS_ID As String, ByVal _REF01 As String, ByVal _REF02 As String)
            Me.HERB_PAYMENTAsync(_IDA, _PROCESS_ID, _REF01, _REF02, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_PAYMENTAsync(ByVal _IDA As Integer, ByVal _PROCESS_ID As String, ByVal _REF01 As String, ByVal _REF02 As String, ByVal userState As Object)
            If (Me.HERB_PAYMENTOperationCompleted Is Nothing) Then
                Me.HERB_PAYMENTOperationCompleted = AddressOf Me.OnHERB_PAYMENTOperationCompleted
            End If
            Me.InvokeAsync("HERB_PAYMENT", New Object() {_IDA, _PROCESS_ID, _REF01, _REF02}, Me.HERB_PAYMENTOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_PAYMENTOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_PAYMENTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_PAYMENTCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/INSERT_HERB_PAYMENT_CENTER_L44", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub INSERT_HERB_PAYMENT_CENTER_L44(ByVal _IDENTIFY As String, ByVal _IDA As Integer, ByVal _PROCESS_ID As String)
            Me.Invoke("INSERT_HERB_PAYMENT_CENTER_L44", New Object() {_IDENTIFY, _IDA, _PROCESS_ID})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub INSERT_HERB_PAYMENT_CENTER_L44Async(ByVal _IDENTIFY As String, ByVal _IDA As Integer, ByVal _PROCESS_ID As String)
            Me.INSERT_HERB_PAYMENT_CENTER_L44Async(_IDENTIFY, _IDA, _PROCESS_ID, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub INSERT_HERB_PAYMENT_CENTER_L44Async(ByVal _IDENTIFY As String, ByVal _IDA As Integer, ByVal _PROCESS_ID As String, ByVal userState As Object)
            If (Me.INSERT_HERB_PAYMENT_CENTER_L44OperationCompleted Is Nothing) Then
                Me.INSERT_HERB_PAYMENT_CENTER_L44OperationCompleted = AddressOf Me.OnINSERT_HERB_PAYMENT_CENTER_L44OperationCompleted
            End If
            Me.InvokeAsync("INSERT_HERB_PAYMENT_CENTER_L44", New Object() {_IDENTIFY, _IDA, _PROCESS_ID}, Me.INSERT_HERB_PAYMENT_CENTER_L44OperationCompleted, userState)
        End Sub
        
        Private Sub OnINSERT_HERB_PAYMENT_CENTER_L44OperationCompleted(ByVal arg As Object)
            If (Not (Me.INSERT_HERB_PAYMENT_CENTER_L44CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent INSERT_HERB_PAYMENT_CENTER_L44Completed(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_PAYMENTCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub INSERT_HERB_PAYMENT_CENTER_L44CompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
End Namespace
