'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class uc_rnp_general_data

    '''<summary>
    '''incorrect_id control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents incorrect_id As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''CheckBox_lcn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_lcn As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_Bsn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_Bsn As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_Phr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_Phr As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_Location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_Location As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_Keep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_Keep As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''CheckBox_Drug_Group control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBox_Drug_Group As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''txt_note_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_note_edit As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Rename_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Rename_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_phr_name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_phr_name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxT_Business_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxT_Business_Name As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''TxT_LCN_NUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TxT_LCN_NUM As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_addr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_addr As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Building control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Building As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_mu control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_mu As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Soi control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Soi As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_road control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_road As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tambol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tambol As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_ampher control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_ampher As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_changwat control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_changwat As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_zipcode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_zipcode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_fax control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_fax As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_tel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_tel As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txt_Opentime control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_Opentime As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rg_bsn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rg_bsn As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rgphr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgphr As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rglocation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rglocation As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''dv_lckeep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dv_lckeep As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rgkeep control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rgkeep As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''rdl_enterprise control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_enterprise As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''rdl_CerSD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_CerSD As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''chk_rad1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chk_rad1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''rdl_cer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdl_cer As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''UC_LCN_DRUG_GROUP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_LCN_DRUG_GROUP As Global.FDA_DRUG_HERB.UC_LCN_DRUG_GROUP
End Class
