'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class POPUP_TABEAN_HERB_EXHIBITION_STAFF_EDIT

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''CHK_TB1_EDIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_TB1_EDIT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbl_tb1_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_tb1_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DIV_SHOW_TXT_EDIT_TB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_SHOW_TXT_EDIT_TB1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''TXT_EDIT_NOTE_TB1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXT_EDIT_NOTE_TB1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''CHK_UPLOAD_EDIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CHK_UPLOAD_EDIT As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbl_upload_edit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_upload_edit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DIV_EDIT_UPLOAD1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_EDIT_UPLOAD1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''NOTE_EDIT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NOTE_EDIT As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UC_ATTACH_LCN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UC_ATTACH_LCN As Global.FDA_DRUG_HERB.UC_ATTACH_LCN

    '''<summary>
    '''img_not control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_not As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''img_cf control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents img_cf As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lbl_upload_file control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_upload_file As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ST_AT control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ST_AT As Global.System.Web.UI.WebControls.HyperLink

    '''<summary>
    '''btn_add_upload control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_add_upload As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DIV_EDIT_UPLOAD2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DIV_EDIT_UPLOAD2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''RadGrid3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid3 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGrid1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid1 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''RadGrid4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadGrid4 As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''lr_preview control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lr_preview As Global.System.Web.UI.WebControls.Literal

    '''<summary>
    '''btn_sumit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_sumit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btn_cancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_cancel As Global.System.Web.UI.WebControls.Button
End Class
