<?xml version="1.0" encoding="utf-8"?><Database Name="FDA_XML_DRUG_HERB" Class="LINQ_FDA_XML_DRUG_HERBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=10.111.28.124;Initial Catalog=FDA_XML_DRUG_HERB;User ID=fusion" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="FDA_XML_DRUG_HERBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.XML_DRUG_LCN_HERB" Member="XML_DRUG_LCN_HERBs">
    <Type Name="XML_DRUG_LCN_HERB">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lcnno" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcntpcd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="GROUPNAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Identify" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_no" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_noo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_not_pvnabbr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="typee" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_addr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_time" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_lo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_addr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thaaddr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tharoom" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thafloor" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thabuilding" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thasoi" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tharoad" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thamu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thathmblnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zipcode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tel" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fax" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm_addr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm_address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thaamphrnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thachngwtnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="cncnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="appdate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="expyear" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grouptype" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Newcode_not" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="LICENSE_NO_SEARCH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LICENSE_NO_SEARCH2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDA_dalcn" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PROCESS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UPDATE_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="pvnabbr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="STATUS_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cnccd" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CER_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XML_DRUG_PRODUCT_HERB" Member="XML_DRUG_PRODUCT_HERBs">
    <Type Name="XML_DRUG_PRODUCT_HERB">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pvncd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="drgtpcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgttpcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="rgtno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thargttpnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engrgttpnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaclassnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engclassnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engdrgtpnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thakindnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engkindnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="register" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rcvno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="register_rcvno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="pvnabbr" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lpvncd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcntpcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="lcnno_no" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="prefix_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="prefix_licen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm_locaion" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_loca" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fulladdr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaaddr_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tharoom_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thafloor_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thabuilding_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thasoi_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tharoad_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thamu_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thathmblnm_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaamphrnm_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thachngwtnm_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="zipcode_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="tel_thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thadrgnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engdrgnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GROUPNAME" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="phm15dgt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Identify" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="drgperunit" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cntcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="thadsgnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engdsgnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ctgthanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="ctgengnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="potency" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="dsgcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ctgcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cnccd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cncnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cnccsnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="cncdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="rcvdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="rcvdate_T" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="appdate_T" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExpiryDate" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="story_edit" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appdate_th" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cncdate_th" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cnsdnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engfrgnnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engfrgnnm_addr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="rid" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="cncdcd" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="expdate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="frn_no" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="itemno" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Ranking" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="typerqt" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Buyers_through" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Buyers_through_cntcd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Newcode" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Newcode_U" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Newcode_R" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Newcode_not" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="register_search" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="register_search2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="indication" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="funcnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDA_drrgt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cncnote" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CER_FORMAT" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="engcntnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDA_dh15rqt" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="pvnabbr2" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XML_DRUG_LCN_LICEN_HERB" Member="XML_DRUG_LCN_LICEN_HERBs">
    <Type Name="XML_DRUG_LCN_LICEN_HERB">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="lcnno" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="pvncd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcntpcd" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="GROUPNAME" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Identify" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_no" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_noo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_not_pvnabbr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="typee" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_addr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_time" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_lo" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_addr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm_addr" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm_address" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thaamphrnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thachngwtnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="cncnm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="appdate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="expyear" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="grouptype" Type="System.String" DbType="NChar(10)" CanBeNull="true" />
      <Column Name="Newcode_not" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="IDA_dalcn" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thachngwtnm_thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thaamphrnm_thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thathmblnm_thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.XML_DRUG_LCN_PHARMACY_HERB" Member="XML_DRUG_LCN_PHARMACY_HERBs">
    <Type Name="XML_DRUG_LCN_PHARMACY_HERB">
      <Column Name="IDA" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="pvncd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnsid" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcntpcd" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_no" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcnno_noo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="CITIZEN_AUTHORIZE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Identify" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="typee" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="licen" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="licen_time" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="grannm_lo" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="pharmacy_name" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phr_addrr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="opentime" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Newcode_not" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="opentime_pharmacy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phrno" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="phrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="lcndtlnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="cncnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="appdate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lmdfdate" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thachngwtnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thaamphrnm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="thanm_addr" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="fk_pharmacy" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="chngwtcd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thachngwtnm_thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="amphrcd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thaamphrnm_thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="thmblcd" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="thathmblnm_thanm" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="fk_ida_dalcn" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>