'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Collections.Generic
Imports System.ComponentModel
Imports System.Data
Imports System.Data.Linq
Imports System.Data.Linq.Mapping
Imports System.Linq
Imports System.Linq.Expressions
Imports System.Reflection


<Global.System.Data.Linq.Mapping.DatabaseAttribute(Name:="LGT_DRUG")>  _
Partial Public Class linq_whoDataContext
	Inherits System.Data.Linq.DataContext
	
	Private Shared mappingSource As System.Data.Linq.Mapping.MappingSource = New AttributeMappingSource()
	
  #Region "Extensibility Method Definitions"
  Partial Private Sub OnCreated()
  End Sub
  Partial Private Sub InsertWHO_DALCN(instance As WHO_DALCN)
    End Sub
  Partial Private Sub UpdateWHO_DALCN(instance As WHO_DALCN)
    End Sub
  Partial Private Sub DeleteWHO_DALCN(instance As WHO_DALCN)
    End Sub
  #End Region
	
	Public Sub New()
		MyBase.New(Global.System.Configuration.ConfigurationManager.ConnectionStrings("LGT_DRUGConnectionString").ConnectionString, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As String, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public Sub New(ByVal connection As System.Data.IDbConnection, ByVal mappingSource As System.Data.Linq.Mapping.MappingSource)
		MyBase.New(connection, mappingSource)
		OnCreated
	End Sub
	
	Public ReadOnly Property WHO_DALCNs() As System.Data.Linq.Table(Of WHO_DALCN)
		Get
			Return Me.GetTable(Of WHO_DALCN)
		End Get
	End Property
End Class

<Global.System.Data.Linq.Mapping.TableAttribute(Name:="dbo.WHO_DALCN")>  _
Partial Public Class WHO_DALCN
	Implements System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	
	Private Shared emptyChangingEventArgs As PropertyChangingEventArgs = New PropertyChangingEventArgs(String.Empty)
	
	Private _IDA As Integer
	
	Private _FK_IDA As System.Nullable(Of Integer)
	
	Private _FK_LCT As System.Nullable(Of Integer)
	
	Private _FK_LCN As System.Nullable(Of Integer)
	
	Private _LCN_TR_ID As System.Nullable(Of Integer)
	
	Private _CITIZEN_ID As String
	
	Private _CITIZEN_ID_AUTHORIZE As String
	
	Private _IDENTIFY As String
	
	Private _LCNSID As System.Nullable(Of Integer)
	
	Private _PREFIXCD As System.Nullable(Of Integer)
	
	Private _PREFIXNM As String
	
	Private _THANM_NAME As String
	
	Private _ADDRESSPERSON As String
	
	Private _TEL As String
	
	Private _EMAIL As String
	
	Private _NOTE As String
	
	Private _MENU_GROUP As System.Nullable(Of Integer)
	
	Private _TYPEPERSON As System.Nullable(Of Integer)
	
	Private _STATUS_ID As System.Nullable(Of Integer)
	
	Private _CREATE_DATE As System.Nullable(Of Date)
	
	Private _CREATE_BY As String
	
	Private _UPDATE_DATE As System.Nullable(Of Date)
	
	Private _UPDATE_BY As String
	
	Private _CITIZEN_ID_ORIGIN As String
	
	Private _CITIZEN_ID_AUTHORIZE_ORIGIN As String
	
	Private _thaaddr As String
	
	Private _tharoom As String
	
	Private _thamu As String
	
	Private _thafloor As String
	
	Private _thasoi As String
	
	Private _thabuilding As String
	
	Private _tharoad As String
	
	Private _zip_code As String
	
	Private _thathmblnm As String
	
	Private _thaamphrnm As String
	
	Private _thachngwtnm As String
	
	Private _fax As String
	
	Private _LOCATION_NAME As String
	
	Private _LCNSID_WHO As System.Nullable(Of Integer)
	
	Private _WHO_NAME As String
	
	Private _ACTIVE As System.Nullable(Of Short)
	
    #Region "Extensibility Method Definitions"
    Partial Private Sub OnLoaded()
    End Sub
    Partial Private Sub OnValidate(action As System.Data.Linq.ChangeAction)
    End Sub
    Partial Private Sub OnCreated()
    End Sub
    Partial Private Sub OnIDAChanging(value As Integer)
    End Sub
    Partial Private Sub OnIDAChanged()
    End Sub
    Partial Private Sub OnFK_IDAChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_IDAChanged()
    End Sub
    Partial Private Sub OnFK_LCTChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_LCTChanged()
    End Sub
    Partial Private Sub OnFK_LCNChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnFK_LCNChanged()
    End Sub
    Partial Private Sub OnLCN_TR_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLCN_TR_IDChanged()
    End Sub
    Partial Private Sub OnCITIZEN_IDChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_IDChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZEChanged()
    End Sub
    Partial Private Sub OnIDENTIFYChanging(value As String)
    End Sub
    Partial Private Sub OnIDENTIFYChanged()
    End Sub
    Partial Private Sub OnLCNSIDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLCNSIDChanged()
    End Sub
    Partial Private Sub OnPREFIXCDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnPREFIXCDChanged()
    End Sub
    Partial Private Sub OnPREFIXNMChanging(value As String)
    End Sub
    Partial Private Sub OnPREFIXNMChanged()
    End Sub
    Partial Private Sub OnTHANM_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnTHANM_NAMEChanged()
    End Sub
    Partial Private Sub OnADDRESSPERSONChanging(value As String)
    End Sub
    Partial Private Sub OnADDRESSPERSONChanged()
    End Sub
    Partial Private Sub OnTELChanging(value As String)
    End Sub
    Partial Private Sub OnTELChanged()
    End Sub
    Partial Private Sub OnEMAILChanging(value As String)
    End Sub
    Partial Private Sub OnEMAILChanged()
    End Sub
    Partial Private Sub OnNOTEChanging(value As String)
    End Sub
    Partial Private Sub OnNOTEChanged()
    End Sub
    Partial Private Sub OnMENU_GROUPChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnMENU_GROUPChanged()
    End Sub
    Partial Private Sub OnTYPEPERSONChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnTYPEPERSONChanged()
    End Sub
    Partial Private Sub OnSTATUS_IDChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnSTATUS_IDChanged()
    End Sub
    Partial Private Sub OnCREATE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnCREATE_DATEChanged()
    End Sub
    Partial Private Sub OnCREATE_BYChanging(value As String)
    End Sub
    Partial Private Sub OnCREATE_BYChanged()
    End Sub
    Partial Private Sub OnUPDATE_DATEChanging(value As System.Nullable(Of Date))
    End Sub
    Partial Private Sub OnUPDATE_DATEChanged()
    End Sub
    Partial Private Sub OnUPDATE_BYChanging(value As String)
    End Sub
    Partial Private Sub OnUPDATE_BYChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_ORIGINChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_ORIGINChanged()
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZE_ORIGINChanging(value As String)
    End Sub
    Partial Private Sub OnCITIZEN_ID_AUTHORIZE_ORIGINChanged()
    End Sub
    Partial Private Sub OnthaaddrChanging(value As String)
    End Sub
    Partial Private Sub OnthaaddrChanged()
    End Sub
    Partial Private Sub OntharoomChanging(value As String)
    End Sub
    Partial Private Sub OntharoomChanged()
    End Sub
    Partial Private Sub OnthamuChanging(value As String)
    End Sub
    Partial Private Sub OnthamuChanged()
    End Sub
    Partial Private Sub OnthafloorChanging(value As String)
    End Sub
    Partial Private Sub OnthafloorChanged()
    End Sub
    Partial Private Sub OnthasoiChanging(value As String)
    End Sub
    Partial Private Sub OnthasoiChanged()
    End Sub
    Partial Private Sub OnthabuildingChanging(value As String)
    End Sub
    Partial Private Sub OnthabuildingChanged()
    End Sub
    Partial Private Sub OntharoadChanging(value As String)
    End Sub
    Partial Private Sub OntharoadChanged()
    End Sub
    Partial Private Sub Onzip_codeChanging(value As String)
    End Sub
    Partial Private Sub Onzip_codeChanged()
    End Sub
    Partial Private Sub OnthathmblnmChanging(value As String)
    End Sub
    Partial Private Sub OnthathmblnmChanged()
    End Sub
    Partial Private Sub OnthaamphrnmChanging(value As String)
    End Sub
    Partial Private Sub OnthaamphrnmChanged()
    End Sub
    Partial Private Sub OnthachngwtnmChanging(value As String)
    End Sub
    Partial Private Sub OnthachngwtnmChanged()
    End Sub
    Partial Private Sub OnfaxChanging(value As String)
    End Sub
    Partial Private Sub OnfaxChanged()
    End Sub
    Partial Private Sub OnLOCATION_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnLOCATION_NAMEChanged()
    End Sub
    Partial Private Sub OnLCNSID_WHOChanging(value As System.Nullable(Of Integer))
    End Sub
    Partial Private Sub OnLCNSID_WHOChanged()
    End Sub
    Partial Private Sub OnWHO_NAMEChanging(value As String)
    End Sub
    Partial Private Sub OnWHO_NAMEChanged()
    End Sub
    Partial Private Sub OnACTIVEChanging(value As System.Nullable(Of Short))
    End Sub
    Partial Private Sub OnACTIVEChanged()
    End Sub
    #End Region
	
	Public Sub New()
		MyBase.New
		OnCreated
	End Sub
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDA", AutoSync:=AutoSync.OnInsert, DbType:="Int NOT NULL IDENTITY", IsPrimaryKey:=true, IsDbGenerated:=true)>  _
	Public Property IDA() As Integer
		Get
			Return Me._IDA
		End Get
		Set
			If ((Me._IDA = value)  _
						= false) Then
				Me.OnIDAChanging(value)
				Me.SendPropertyChanging
				Me._IDA = value
				Me.SendPropertyChanged("IDA")
				Me.OnIDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_IDA", DbType:="Int")>  _
	Public Property FK_IDA() As System.Nullable(Of Integer)
		Get
			Return Me._FK_IDA
		End Get
		Set
			If (Me._FK_IDA.Equals(value) = false) Then
				Me.OnFK_IDAChanging(value)
				Me.SendPropertyChanging
				Me._FK_IDA = value
				Me.SendPropertyChanged("FK_IDA")
				Me.OnFK_IDAChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_LCT", DbType:="Int")>  _
	Public Property FK_LCT() As System.Nullable(Of Integer)
		Get
			Return Me._FK_LCT
		End Get
		Set
			If (Me._FK_LCT.Equals(value) = false) Then
				Me.OnFK_LCTChanging(value)
				Me.SendPropertyChanging
				Me._FK_LCT = value
				Me.SendPropertyChanged("FK_LCT")
				Me.OnFK_LCTChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_FK_LCN", DbType:="Int")>  _
	Public Property FK_LCN() As System.Nullable(Of Integer)
		Get
			Return Me._FK_LCN
		End Get
		Set
			If (Me._FK_LCN.Equals(value) = false) Then
				Me.OnFK_LCNChanging(value)
				Me.SendPropertyChanging
				Me._FK_LCN = value
				Me.SendPropertyChanged("FK_LCN")
				Me.OnFK_LCNChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCN_TR_ID", DbType:="Int")>  _
	Public Property LCN_TR_ID() As System.Nullable(Of Integer)
		Get
			Return Me._LCN_TR_ID
		End Get
		Set
			If (Me._LCN_TR_ID.Equals(value) = false) Then
				Me.OnLCN_TR_IDChanging(value)
				Me.SendPropertyChanging
				Me._LCN_TR_ID = value
				Me.SendPropertyChanged("LCN_TR_ID")
				Me.OnLCN_TR_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID", DbType:="NVarChar(13)")>  _
	Public Property CITIZEN_ID() As String
		Get
			Return Me._CITIZEN_ID
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID, value) = false) Then
				Me.OnCITIZEN_IDChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID = value
				Me.SendPropertyChanged("CITIZEN_ID")
				Me.OnCITIZEN_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_AUTHORIZE", DbType:="NVarChar(13)")>  _
	Public Property CITIZEN_ID_AUTHORIZE() As String
		Get
			Return Me._CITIZEN_ID_AUTHORIZE
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_AUTHORIZE, value) = false) Then
				Me.OnCITIZEN_ID_AUTHORIZEChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_AUTHORIZE = value
				Me.SendPropertyChanged("CITIZEN_ID_AUTHORIZE")
				Me.OnCITIZEN_ID_AUTHORIZEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_IDENTIFY", DbType:="NVarChar(13)")>  _
	Public Property IDENTIFY() As String
		Get
			Return Me._IDENTIFY
		End Get
		Set
			If (String.Equals(Me._IDENTIFY, value) = false) Then
				Me.OnIDENTIFYChanging(value)
				Me.SendPropertyChanging
				Me._IDENTIFY = value
				Me.SendPropertyChanged("IDENTIFY")
				Me.OnIDENTIFYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNSID", DbType:="Int")>  _
	Public Property LCNSID() As System.Nullable(Of Integer)
		Get
			Return Me._LCNSID
		End Get
		Set
			If (Me._LCNSID.Equals(value) = false) Then
				Me.OnLCNSIDChanging(value)
				Me.SendPropertyChanging
				Me._LCNSID = value
				Me.SendPropertyChanged("LCNSID")
				Me.OnLCNSIDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREFIXCD", DbType:="Int")>  _
	Public Property PREFIXCD() As System.Nullable(Of Integer)
		Get
			Return Me._PREFIXCD
		End Get
		Set
			If (Me._PREFIXCD.Equals(value) = false) Then
				Me.OnPREFIXCDChanging(value)
				Me.SendPropertyChanging
				Me._PREFIXCD = value
				Me.SendPropertyChanged("PREFIXCD")
				Me.OnPREFIXCDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_PREFIXNM", DbType:="VarChar(MAX)")>  _
	Public Property PREFIXNM() As String
		Get
			Return Me._PREFIXNM
		End Get
		Set
			If (String.Equals(Me._PREFIXNM, value) = false) Then
				Me.OnPREFIXNMChanging(value)
				Me.SendPropertyChanging
				Me._PREFIXNM = value
				Me.SendPropertyChanged("PREFIXNM")
				Me.OnPREFIXNMChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_THANM_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property THANM_NAME() As String
		Get
			Return Me._THANM_NAME
		End Get
		Set
			If (String.Equals(Me._THANM_NAME, value) = false) Then
				Me.OnTHANM_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._THANM_NAME = value
				Me.SendPropertyChanged("THANM_NAME")
				Me.OnTHANM_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ADDRESSPERSON", DbType:="NVarChar(MAX)")>  _
	Public Property ADDRESSPERSON() As String
		Get
			Return Me._ADDRESSPERSON
		End Get
		Set
			If (String.Equals(Me._ADDRESSPERSON, value) = false) Then
				Me.OnADDRESSPERSONChanging(value)
				Me.SendPropertyChanging
				Me._ADDRESSPERSON = value
				Me.SendPropertyChanged("ADDRESSPERSON")
				Me.OnADDRESSPERSONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TEL", DbType:="NVarChar(MAX)")>  _
	Public Property TEL() As String
		Get
			Return Me._TEL
		End Get
		Set
			If (String.Equals(Me._TEL, value) = false) Then
				Me.OnTELChanging(value)
				Me.SendPropertyChanging
				Me._TEL = value
				Me.SendPropertyChanged("TEL")
				Me.OnTELChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_EMAIL", DbType:="NVarChar(MAX)")>  _
	Public Property EMAIL() As String
		Get
			Return Me._EMAIL
		End Get
		Set
			If (String.Equals(Me._EMAIL, value) = false) Then
				Me.OnEMAILChanging(value)
				Me.SendPropertyChanging
				Me._EMAIL = value
				Me.SendPropertyChanged("EMAIL")
				Me.OnEMAILChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_NOTE", DbType:="NVarChar(MAX)")>  _
	Public Property NOTE() As String
		Get
			Return Me._NOTE
		End Get
		Set
			If (String.Equals(Me._NOTE, value) = false) Then
				Me.OnNOTEChanging(value)
				Me.SendPropertyChanging
				Me._NOTE = value
				Me.SendPropertyChanged("NOTE")
				Me.OnNOTEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_MENU_GROUP", DbType:="Int")>  _
	Public Property MENU_GROUP() As System.Nullable(Of Integer)
		Get
			Return Me._MENU_GROUP
		End Get
		Set
			If (Me._MENU_GROUP.Equals(value) = false) Then
				Me.OnMENU_GROUPChanging(value)
				Me.SendPropertyChanging
				Me._MENU_GROUP = value
				Me.SendPropertyChanged("MENU_GROUP")
				Me.OnMENU_GROUPChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_TYPEPERSON", DbType:="Int")>  _
	Public Property TYPEPERSON() As System.Nullable(Of Integer)
		Get
			Return Me._TYPEPERSON
		End Get
		Set
			If (Me._TYPEPERSON.Equals(value) = false) Then
				Me.OnTYPEPERSONChanging(value)
				Me.SendPropertyChanging
				Me._TYPEPERSON = value
				Me.SendPropertyChanged("TYPEPERSON")
				Me.OnTYPEPERSONChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_STATUS_ID", DbType:="Int")>  _
	Public Property STATUS_ID() As System.Nullable(Of Integer)
		Get
			Return Me._STATUS_ID
		End Get
		Set
			If (Me._STATUS_ID.Equals(value) = false) Then
				Me.OnSTATUS_IDChanging(value)
				Me.SendPropertyChanging
				Me._STATUS_ID = value
				Me.SendPropertyChanged("STATUS_ID")
				Me.OnSTATUS_IDChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_DATE", DbType:="DateTime")>  _
	Public Property CREATE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._CREATE_DATE
		End Get
		Set
			If (Me._CREATE_DATE.Equals(value) = false) Then
				Me.OnCREATE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_DATE = value
				Me.SendPropertyChanged("CREATE_DATE")
				Me.OnCREATE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CREATE_BY", DbType:="NVarChar(MAX)")>  _
	Public Property CREATE_BY() As String
		Get
			Return Me._CREATE_BY
		End Get
		Set
			If (String.Equals(Me._CREATE_BY, value) = false) Then
				Me.OnCREATE_BYChanging(value)
				Me.SendPropertyChanging
				Me._CREATE_BY = value
				Me.SendPropertyChanged("CREATE_BY")
				Me.OnCREATE_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UPDATE_DATE", DbType:="DateTime")>  _
	Public Property UPDATE_DATE() As System.Nullable(Of Date)
		Get
			Return Me._UPDATE_DATE
		End Get
		Set
			If (Me._UPDATE_DATE.Equals(value) = false) Then
				Me.OnUPDATE_DATEChanging(value)
				Me.SendPropertyChanging
				Me._UPDATE_DATE = value
				Me.SendPropertyChanged("UPDATE_DATE")
				Me.OnUPDATE_DATEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_UPDATE_BY", DbType:="NVarChar(MAX)")>  _
	Public Property UPDATE_BY() As String
		Get
			Return Me._UPDATE_BY
		End Get
		Set
			If (String.Equals(Me._UPDATE_BY, value) = false) Then
				Me.OnUPDATE_BYChanging(value)
				Me.SendPropertyChanging
				Me._UPDATE_BY = value
				Me.SendPropertyChanged("UPDATE_BY")
				Me.OnUPDATE_BYChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_ORIGIN", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID_ORIGIN() As String
		Get
			Return Me._CITIZEN_ID_ORIGIN
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_ORIGIN, value) = false) Then
				Me.OnCITIZEN_ID_ORIGINChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_ORIGIN = value
				Me.SendPropertyChanged("CITIZEN_ID_ORIGIN")
				Me.OnCITIZEN_ID_ORIGINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_CITIZEN_ID_AUTHORIZE_ORIGIN", DbType:="NVarChar(MAX)")>  _
	Public Property CITIZEN_ID_AUTHORIZE_ORIGIN() As String
		Get
			Return Me._CITIZEN_ID_AUTHORIZE_ORIGIN
		End Get
		Set
			If (String.Equals(Me._CITIZEN_ID_AUTHORIZE_ORIGIN, value) = false) Then
				Me.OnCITIZEN_ID_AUTHORIZE_ORIGINChanging(value)
				Me.SendPropertyChanging
				Me._CITIZEN_ID_AUTHORIZE_ORIGIN = value
				Me.SendPropertyChanged("CITIZEN_ID_AUTHORIZE_ORIGIN")
				Me.OnCITIZEN_ID_AUTHORIZE_ORIGINChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thaaddr", DbType:="NVarChar(MAX)")>  _
	Public Property thaaddr() As String
		Get
			Return Me._thaaddr
		End Get
		Set
			If (String.Equals(Me._thaaddr, value) = false) Then
				Me.OnthaaddrChanging(value)
				Me.SendPropertyChanging
				Me._thaaddr = value
				Me.SendPropertyChanged("thaaddr")
				Me.OnthaaddrChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tharoom", DbType:="NVarChar(MAX)")>  _
	Public Property tharoom() As String
		Get
			Return Me._tharoom
		End Get
		Set
			If (String.Equals(Me._tharoom, value) = false) Then
				Me.OntharoomChanging(value)
				Me.SendPropertyChanging
				Me._tharoom = value
				Me.SendPropertyChanged("tharoom")
				Me.OntharoomChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thamu", DbType:="NVarChar(MAX)")>  _
	Public Property thamu() As String
		Get
			Return Me._thamu
		End Get
		Set
			If (String.Equals(Me._thamu, value) = false) Then
				Me.OnthamuChanging(value)
				Me.SendPropertyChanging
				Me._thamu = value
				Me.SendPropertyChanged("thamu")
				Me.OnthamuChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thafloor", DbType:="NVarChar(MAX)")>  _
	Public Property thafloor() As String
		Get
			Return Me._thafloor
		End Get
		Set
			If (String.Equals(Me._thafloor, value) = false) Then
				Me.OnthafloorChanging(value)
				Me.SendPropertyChanging
				Me._thafloor = value
				Me.SendPropertyChanged("thafloor")
				Me.OnthafloorChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thasoi", DbType:="NVarChar(MAX)")>  _
	Public Property thasoi() As String
		Get
			Return Me._thasoi
		End Get
		Set
			If (String.Equals(Me._thasoi, value) = false) Then
				Me.OnthasoiChanging(value)
				Me.SendPropertyChanging
				Me._thasoi = value
				Me.SendPropertyChanged("thasoi")
				Me.OnthasoiChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thabuilding", DbType:="NVarChar(MAX)")>  _
	Public Property thabuilding() As String
		Get
			Return Me._thabuilding
		End Get
		Set
			If (String.Equals(Me._thabuilding, value) = false) Then
				Me.OnthabuildingChanging(value)
				Me.SendPropertyChanging
				Me._thabuilding = value
				Me.SendPropertyChanged("thabuilding")
				Me.OnthabuildingChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_tharoad", DbType:="NVarChar(MAX)")>  _
	Public Property tharoad() As String
		Get
			Return Me._tharoad
		End Get
		Set
			If (String.Equals(Me._tharoad, value) = false) Then
				Me.OntharoadChanging(value)
				Me.SendPropertyChanging
				Me._tharoad = value
				Me.SendPropertyChanged("tharoad")
				Me.OntharoadChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_zip_code", DbType:="NVarChar(MAX)")>  _
	Public Property zip_code() As String
		Get
			Return Me._zip_code
		End Get
		Set
			If (String.Equals(Me._zip_code, value) = false) Then
				Me.Onzip_codeChanging(value)
				Me.SendPropertyChanging
				Me._zip_code = value
				Me.SendPropertyChanged("zip_code")
				Me.Onzip_codeChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thathmblnm", DbType:="NVarChar(MAX)")>  _
	Public Property thathmblnm() As String
		Get
			Return Me._thathmblnm
		End Get
		Set
			If (String.Equals(Me._thathmblnm, value) = false) Then
				Me.OnthathmblnmChanging(value)
				Me.SendPropertyChanging
				Me._thathmblnm = value
				Me.SendPropertyChanged("thathmblnm")
				Me.OnthathmblnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thaamphrnm", DbType:="NVarChar(MAX)")>  _
	Public Property thaamphrnm() As String
		Get
			Return Me._thaamphrnm
		End Get
		Set
			If (String.Equals(Me._thaamphrnm, value) = false) Then
				Me.OnthaamphrnmChanging(value)
				Me.SendPropertyChanging
				Me._thaamphrnm = value
				Me.SendPropertyChanged("thaamphrnm")
				Me.OnthaamphrnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_thachngwtnm", DbType:="NVarChar(MAX)")>  _
	Public Property thachngwtnm() As String
		Get
			Return Me._thachngwtnm
		End Get
		Set
			If (String.Equals(Me._thachngwtnm, value) = false) Then
				Me.OnthachngwtnmChanging(value)
				Me.SendPropertyChanging
				Me._thachngwtnm = value
				Me.SendPropertyChanged("thachngwtnm")
				Me.OnthachngwtnmChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_fax", DbType:="NVarChar(MAX)")>  _
	Public Property fax() As String
		Get
			Return Me._fax
		End Get
		Set
			If (String.Equals(Me._fax, value) = false) Then
				Me.OnfaxChanging(value)
				Me.SendPropertyChanging
				Me._fax = value
				Me.SendPropertyChanged("fax")
				Me.OnfaxChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LOCATION_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property LOCATION_NAME() As String
		Get
			Return Me._LOCATION_NAME
		End Get
		Set
			If (String.Equals(Me._LOCATION_NAME, value) = false) Then
				Me.OnLOCATION_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._LOCATION_NAME = value
				Me.SendPropertyChanged("LOCATION_NAME")
				Me.OnLOCATION_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_LCNSID_WHO", DbType:="Int")>  _
	Public Property LCNSID_WHO() As System.Nullable(Of Integer)
		Get
			Return Me._LCNSID_WHO
		End Get
		Set
			If (Me._LCNSID_WHO.Equals(value) = false) Then
				Me.OnLCNSID_WHOChanging(value)
				Me.SendPropertyChanging
				Me._LCNSID_WHO = value
				Me.SendPropertyChanged("LCNSID_WHO")
				Me.OnLCNSID_WHOChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_WHO_NAME", DbType:="NVarChar(MAX)")>  _
	Public Property WHO_NAME() As String
		Get
			Return Me._WHO_NAME
		End Get
		Set
			If (String.Equals(Me._WHO_NAME, value) = false) Then
				Me.OnWHO_NAMEChanging(value)
				Me.SendPropertyChanging
				Me._WHO_NAME = value
				Me.SendPropertyChanged("WHO_NAME")
				Me.OnWHO_NAMEChanged
			End If
		End Set
	End Property
	
	<Global.System.Data.Linq.Mapping.ColumnAttribute(Storage:="_ACTIVE", DbType:="SmallInt")>  _
	Public Property ACTIVE() As System.Nullable(Of Short)
		Get
			Return Me._ACTIVE
		End Get
		Set
			If (Me._ACTIVE.Equals(value) = false) Then
				Me.OnACTIVEChanging(value)
				Me.SendPropertyChanging
				Me._ACTIVE = value
				Me.SendPropertyChanged("ACTIVE")
				Me.OnACTIVEChanged
			End If
		End Set
	End Property
	
	Public Event PropertyChanging As PropertyChangingEventHandler Implements System.ComponentModel.INotifyPropertyChanging.PropertyChanging
	
	Public Event PropertyChanged As PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
	
	Protected Overridable Sub SendPropertyChanging()
		If ((Me.PropertyChangingEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanging(Me, emptyChangingEventArgs)
		End If
	End Sub
	
	Protected Overridable Sub SendPropertyChanged(ByVal propertyName As [String])
		If ((Me.PropertyChangedEvent Is Nothing)  _
					= false) Then
			RaiseEvent PropertyChanged(Me, New PropertyChangedEventArgs(propertyName))
		End If
	End Sub
End Class
