'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Data
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
'
Namespace WS_DRUG
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="WS_DRUGSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class WS_DRUG
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private HERB_INSERT_LICENOperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_INSERT_XML_LICEN_ALLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_UPDATE_LICENOperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_INSERT_DR15OperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_UPDATE_DH15OperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_INSERT_DR15_DEMOOperationCompleted As System.Threading.SendOrPostCallback
        
        Private UPDATE_TRANFERS_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private UPDATE_SMP_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_INSERT_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private UPDATE_DR_HERB_FOROperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_UPDATE_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_DELETE_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_INSERT_XML_PRODUCT_ALLOperationCompleted As System.Threading.SendOrPostCallback
        
        Private HERB_UPDATE_XML_PRODUCTOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_DRUG_BC_UPDATE_TBOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_DRUG_FORMULAOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_DRUG_LICENSEOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_GET_SEARCH_DRUG_DR_IOW_ESUBOperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_GET_SEARCH_DRUG_DROperationCompleted As System.Threading.SendOrPostCallback
        
        Private XML_GET_SEARCH_DRUG_LCNOperationCompleted As System.Threading.SendOrPostCallback
        
        Private LOG_EDIT_TABEAN_HERBOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.FDA_DRUG_HERB.My.MySettings.Default.FDA_DRUG_HERB_WS_DRUG_WS_DRUG
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event HERB_INSERT_LICENCompleted As HERB_INSERT_LICENCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_INSERT_XML_LICEN_ALLCompleted As HERB_INSERT_XML_LICEN_ALLCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_UPDATE_LICENCompleted As HERB_UPDATE_LICENCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_INSERT_DR15Completed As HERB_INSERT_DR15CompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_UPDATE_DH15Completed As HERB_UPDATE_DH15CompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_INSERT_DR15_DEMOCompleted As HERB_INSERT_DR15_DEMOCompletedEventHandler
        
        '''<remarks/>
        Public Event UPDATE_TRANFERS_DRCompleted As UPDATE_TRANFERS_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event UPDATE_SMP_DRCompleted As UPDATE_SMP_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_INSERT_DRCompleted As HERB_INSERT_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event UPDATE_DR_HERB_FORCompleted As UPDATE_DR_HERB_FORCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_UPDATE_DRCompleted As HERB_UPDATE_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_DELETE_DRCompleted As HERB_DELETE_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_INSERT_XML_PRODUCT_ALLCompleted As HERB_INSERT_XML_PRODUCT_ALLCompletedEventHandler
        
        '''<remarks/>
        Public Event HERB_UPDATE_XML_PRODUCTCompleted As HERB_UPDATE_XML_PRODUCTCompletedEventHandler
        
        '''<remarks/>
        Public Event XML_DRUG_BC_UPDATE_TBCompleted As XML_DRUG_BC_UPDATE_TBCompletedEventHandler
        
        '''<remarks/>
        Public Event XML_DRUG_FORMULACompleted As XML_DRUG_FORMULACompletedEventHandler
        
        '''<remarks/>
        Public Event XML_DRUG_LICENSECompleted As XML_DRUG_LICENSECompletedEventHandler
        
        '''<remarks/>
        Public Event XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompleted As XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompletedEventHandler
        
        '''<remarks/>
        Public Event XML_GET_SEARCH_DRUG_DRCompleted As XML_GET_SEARCH_DRUG_DRCompletedEventHandler
        
        '''<remarks/>
        Public Event XML_GET_SEARCH_DRUG_LCNCompleted As XML_GET_SEARCH_DRUG_LCNCompletedEventHandler
        
        '''<remarks/>
        Public Event LOG_EDIT_TABEAN_HERBCompleted As LOG_EDIT_TABEAN_HERBCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_INSERT_LICEN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_INSERT_LICEN(ByVal IDA_dalcn As Integer, ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("HERB_INSERT_LICEN", New Object() {IDA_dalcn, IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_LICENAsync(ByVal IDA_dalcn As Integer, ByVal IDENTIFY_EDIT As String)
            Me.HERB_INSERT_LICENAsync(IDA_dalcn, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_LICENAsync(ByVal IDA_dalcn As Integer, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.HERB_INSERT_LICENOperationCompleted Is Nothing) Then
                Me.HERB_INSERT_LICENOperationCompleted = AddressOf Me.OnHERB_INSERT_LICENOperationCompleted
            End If
            Me.InvokeAsync("HERB_INSERT_LICEN", New Object() {IDA_dalcn, IDENTIFY_EDIT}, Me.HERB_INSERT_LICENOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_INSERT_LICENOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_INSERT_LICENCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_INSERT_LICENCompleted(Me, New HERB_INSERT_LICENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_INSERT_XML_LICEN_ALL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_INSERT_XML_LICEN_ALL(ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("HERB_INSERT_XML_LICEN_ALL", New Object() {IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_XML_LICEN_ALLAsync(ByVal IDENTIFY_EDIT As String)
            Me.HERB_INSERT_XML_LICEN_ALLAsync(IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_XML_LICEN_ALLAsync(ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.HERB_INSERT_XML_LICEN_ALLOperationCompleted Is Nothing) Then
                Me.HERB_INSERT_XML_LICEN_ALLOperationCompleted = AddressOf Me.OnHERB_INSERT_XML_LICEN_ALLOperationCompleted
            End If
            Me.InvokeAsync("HERB_INSERT_XML_LICEN_ALL", New Object() {IDENTIFY_EDIT}, Me.HERB_INSERT_XML_LICEN_ALLOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_INSERT_XML_LICEN_ALLOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_INSERT_XML_LICEN_ALLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_INSERT_XML_LICEN_ALLCompleted(Me, New HERB_INSERT_XML_LICEN_ALLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_UPDATE_LICEN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_UPDATE_LICEN(ByVal IDA_dalcn As Integer, ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("HERB_UPDATE_LICEN", New Object() {IDA_dalcn, IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_LICENAsync(ByVal IDA_dalcn As Integer, ByVal IDENTIFY_EDIT As String)
            Me.HERB_UPDATE_LICENAsync(IDA_dalcn, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_LICENAsync(ByVal IDA_dalcn As Integer, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.HERB_UPDATE_LICENOperationCompleted Is Nothing) Then
                Me.HERB_UPDATE_LICENOperationCompleted = AddressOf Me.OnHERB_UPDATE_LICENOperationCompleted
            End If
            Me.InvokeAsync("HERB_UPDATE_LICEN", New Object() {IDA_dalcn, IDENTIFY_EDIT}, Me.HERB_UPDATE_LICENOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_UPDATE_LICENOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_UPDATE_LICENCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_UPDATE_LICENCompleted(Me, New HERB_UPDATE_LICENCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_INSERT_DR15", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_INSERT_DR15(ByVal IDA_DH15 As Integer, ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("HERB_INSERT_DR15", New Object() {IDA_DH15, IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_DR15Async(ByVal IDA_DH15 As Integer, ByVal IDENTIFY_EDIT As String)
            Me.HERB_INSERT_DR15Async(IDA_DH15, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_DR15Async(ByVal IDA_DH15 As Integer, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.HERB_INSERT_DR15OperationCompleted Is Nothing) Then
                Me.HERB_INSERT_DR15OperationCompleted = AddressOf Me.OnHERB_INSERT_DR15OperationCompleted
            End If
            Me.InvokeAsync("HERB_INSERT_DR15", New Object() {IDA_DH15, IDENTIFY_EDIT}, Me.HERB_INSERT_DR15OperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_INSERT_DR15OperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_INSERT_DR15CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_INSERT_DR15Completed(Me, New HERB_INSERT_DR15CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_UPDATE_DH15", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_UPDATE_DH15(ByVal IDA_DH15 As Integer, ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("HERB_UPDATE_DH15", New Object() {IDA_DH15, IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_DH15Async(ByVal IDA_DH15 As Integer, ByVal IDENTIFY_EDIT As String)
            Me.HERB_UPDATE_DH15Async(IDA_DH15, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_DH15Async(ByVal IDA_DH15 As Integer, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.HERB_UPDATE_DH15OperationCompleted Is Nothing) Then
                Me.HERB_UPDATE_DH15OperationCompleted = AddressOf Me.OnHERB_UPDATE_DH15OperationCompleted
            End If
            Me.InvokeAsync("HERB_UPDATE_DH15", New Object() {IDA_DH15, IDENTIFY_EDIT}, Me.HERB_UPDATE_DH15OperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_UPDATE_DH15OperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_UPDATE_DH15CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_UPDATE_DH15Completed(Me, New HERB_UPDATE_DH15CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_INSERT_DR15_DEMO", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_INSERT_DR15_DEMO(ByVal phm15dgt As String) As String
            Dim results() As Object = Me.Invoke("HERB_INSERT_DR15_DEMO", New Object() {phm15dgt})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_DR15_DEMOAsync(ByVal phm15dgt As String)
            Me.HERB_INSERT_DR15_DEMOAsync(phm15dgt, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_DR15_DEMOAsync(ByVal phm15dgt As String, ByVal userState As Object)
            If (Me.HERB_INSERT_DR15_DEMOOperationCompleted Is Nothing) Then
                Me.HERB_INSERT_DR15_DEMOOperationCompleted = AddressOf Me.OnHERB_INSERT_DR15_DEMOOperationCompleted
            End If
            Me.InvokeAsync("HERB_INSERT_DR15_DEMO", New Object() {phm15dgt}, Me.HERB_INSERT_DR15_DEMOOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_INSERT_DR15_DEMOOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_INSERT_DR15_DEMOCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_INSERT_DR15_DEMOCompleted(Me, New HERB_INSERT_DR15_DEMOCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_TRANFERS_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UPDATE_TRANFERS_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("UPDATE_TRANFERS_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UPDATE_TRANFERS_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.UPDATE_TRANFERS_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UPDATE_TRANFERS_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.UPDATE_TRANFERS_DROperationCompleted Is Nothing) Then
                Me.UPDATE_TRANFERS_DROperationCompleted = AddressOf Me.OnUPDATE_TRANFERS_DROperationCompleted
            End If
            Me.InvokeAsync("UPDATE_TRANFERS_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system}, Me.UPDATE_TRANFERS_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnUPDATE_TRANFERS_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.UPDATE_TRANFERS_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UPDATE_TRANFERS_DRCompleted(Me, New UPDATE_TRANFERS_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_SMP_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UPDATE_SMP_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("UPDATE_SMP_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UPDATE_SMP_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.UPDATE_SMP_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UPDATE_SMP_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.UPDATE_SMP_DROperationCompleted Is Nothing) Then
                Me.UPDATE_SMP_DROperationCompleted = AddressOf Me.OnUPDATE_SMP_DROperationCompleted
            End If
            Me.InvokeAsync("UPDATE_SMP_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system}, Me.UPDATE_SMP_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnUPDATE_SMP_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.UPDATE_SMP_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UPDATE_SMP_DRCompleted(Me, New UPDATE_SMP_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_INSERT_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_INSERT_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("HERB_INSERT_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.HERB_INSERT_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.HERB_INSERT_DROperationCompleted Is Nothing) Then
                Me.HERB_INSERT_DROperationCompleted = AddressOf Me.OnHERB_INSERT_DROperationCompleted
            End If
            Me.InvokeAsync("HERB_INSERT_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system}, Me.HERB_INSERT_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_INSERT_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_INSERT_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_INSERT_DRCompleted(Me, New HERB_INSERT_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/UPDATE_DR_HERB_FOR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function UPDATE_DR_HERB_FOR(ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("UPDATE_DR_HERB_FOR", New Object() {remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub UPDATE_DR_HERB_FORAsync(ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.UPDATE_DR_HERB_FORAsync(remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub UPDATE_DR_HERB_FORAsync(ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.UPDATE_DR_HERB_FOROperationCompleted Is Nothing) Then
                Me.UPDATE_DR_HERB_FOROperationCompleted = AddressOf Me.OnUPDATE_DR_HERB_FOROperationCompleted
            End If
            Me.InvokeAsync("UPDATE_DR_HERB_FOR", New Object() {remark, IDENTIFY_EDIT, system}, Me.UPDATE_DR_HERB_FOROperationCompleted, userState)
        End Sub
        
        Private Sub OnUPDATE_DR_HERB_FOROperationCompleted(ByVal arg As Object)
            If (Not (Me.UPDATE_DR_HERB_FORCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent UPDATE_DR_HERB_FORCompleted(Me, New UPDATE_DR_HERB_FORCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_UPDATE_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_UPDATE_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("HERB_UPDATE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.HERB_UPDATE_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.HERB_UPDATE_DROperationCompleted Is Nothing) Then
                Me.HERB_UPDATE_DROperationCompleted = AddressOf Me.OnHERB_UPDATE_DROperationCompleted
            End If
            Me.InvokeAsync("HERB_UPDATE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system}, Me.HERB_UPDATE_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_UPDATE_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_UPDATE_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_UPDATE_DRCompleted(Me, New HERB_UPDATE_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_DELETE_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_DELETE_DR(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("HERB_DELETE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_DELETE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.HERB_DELETE_DRAsync(pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_DELETE_DRAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.HERB_DELETE_DROperationCompleted Is Nothing) Then
                Me.HERB_DELETE_DROperationCompleted = AddressOf Me.OnHERB_DELETE_DROperationCompleted
            End If
            Me.InvokeAsync("HERB_DELETE_DR", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system}, Me.HERB_DELETE_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_DELETE_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_DELETE_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_DELETE_DRCompleted(Me, New HERB_DELETE_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_INSERT_XML_PRODUCT_ALL", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_INSERT_XML_PRODUCT_ALL(ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("HERB_INSERT_XML_PRODUCT_ALL", New Object() {IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_XML_PRODUCT_ALLAsync(ByVal IDENTIFY_EDIT As String)
            Me.HERB_INSERT_XML_PRODUCT_ALLAsync(IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_INSERT_XML_PRODUCT_ALLAsync(ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.HERB_INSERT_XML_PRODUCT_ALLOperationCompleted Is Nothing) Then
                Me.HERB_INSERT_XML_PRODUCT_ALLOperationCompleted = AddressOf Me.OnHERB_INSERT_XML_PRODUCT_ALLOperationCompleted
            End If
            Me.InvokeAsync("HERB_INSERT_XML_PRODUCT_ALL", New Object() {IDENTIFY_EDIT}, Me.HERB_INSERT_XML_PRODUCT_ALLOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_INSERT_XML_PRODUCT_ALLOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_INSERT_XML_PRODUCT_ALLCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_INSERT_XML_PRODUCT_ALLCompleted(Me, New HERB_INSERT_XML_PRODUCT_ALLCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HERB_UPDATE_XML_PRODUCT", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function HERB_UPDATE_XML_PRODUCT(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String) As String
            Dim results() As Object = Me.Invoke("HERB_UPDATE_XML_PRODUCT", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_XML_PRODUCTAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String)
            Me.HERB_UPDATE_XML_PRODUCTAsync(pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub HERB_UPDATE_XML_PRODUCTAsync(ByVal pvncd As String, ByVal rgttpcd As String, ByVal drgtpcd As String, ByVal rgtno As String, ByVal remark As String, ByVal IDENTIFY_EDIT As String, ByVal system As String, ByVal userState As Object)
            If (Me.HERB_UPDATE_XML_PRODUCTOperationCompleted Is Nothing) Then
                Me.HERB_UPDATE_XML_PRODUCTOperationCompleted = AddressOf Me.OnHERB_UPDATE_XML_PRODUCTOperationCompleted
            End If
            Me.InvokeAsync("HERB_UPDATE_XML_PRODUCT", New Object() {pvncd, rgttpcd, drgtpcd, rgtno, remark, IDENTIFY_EDIT, system}, Me.HERB_UPDATE_XML_PRODUCTOperationCompleted, userState)
        End Sub
        
        Private Sub OnHERB_UPDATE_XML_PRODUCTOperationCompleted(ByVal arg As Object)
            If (Not (Me.HERB_UPDATE_XML_PRODUCTCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent HERB_UPDATE_XML_PRODUCTCompleted(Me, New HERB_UPDATE_XML_PRODUCTCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_DRUG_BC_UPDATE_TB", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub XML_DRUG_BC_UPDATE_TB(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String)
            Me.Invoke("XML_DRUG_BC_UPDATE_TB", New Object() {Newcode, IDENTIFY_EDIT})
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_BC_UPDATE_TBAsync(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String)
            Me.XML_DRUG_BC_UPDATE_TBAsync(Newcode, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_BC_UPDATE_TBAsync(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.XML_DRUG_BC_UPDATE_TBOperationCompleted Is Nothing) Then
                Me.XML_DRUG_BC_UPDATE_TBOperationCompleted = AddressOf Me.OnXML_DRUG_BC_UPDATE_TBOperationCompleted
            End If
            Me.InvokeAsync("XML_DRUG_BC_UPDATE_TB", New Object() {Newcode, IDENTIFY_EDIT}, Me.XML_DRUG_BC_UPDATE_TBOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_DRUG_BC_UPDATE_TBOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_DRUG_BC_UPDATE_TBCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_DRUG_BC_UPDATE_TBCompleted(Me, New System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_DRUG_FORMULA", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function XML_DRUG_FORMULA(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String) As String
            Dim results() As Object = Me.Invoke("XML_DRUG_FORMULA", New Object() {Newcode, IDENTIFY_EDIT})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_FORMULAAsync(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String)
            Me.XML_DRUG_FORMULAAsync(Newcode, IDENTIFY_EDIT, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_FORMULAAsync(ByVal Newcode As String, ByVal IDENTIFY_EDIT As String, ByVal userState As Object)
            If (Me.XML_DRUG_FORMULAOperationCompleted Is Nothing) Then
                Me.XML_DRUG_FORMULAOperationCompleted = AddressOf Me.OnXML_DRUG_FORMULAOperationCompleted
            End If
            Me.InvokeAsync("XML_DRUG_FORMULA", New Object() {Newcode, IDENTIFY_EDIT}, Me.XML_DRUG_FORMULAOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_DRUG_FORMULAOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_DRUG_FORMULACompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_DRUG_FORMULACompleted(Me, New XML_DRUG_FORMULACompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_DRUG_LICENSE", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function XML_DRUG_LICENSE(ByVal Newcode As String) As String
            Dim results() As Object = Me.Invoke("XML_DRUG_LICENSE", New Object() {Newcode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_LICENSEAsync(ByVal Newcode As String)
            Me.XML_DRUG_LICENSEAsync(Newcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_DRUG_LICENSEAsync(ByVal Newcode As String, ByVal userState As Object)
            If (Me.XML_DRUG_LICENSEOperationCompleted Is Nothing) Then
                Me.XML_DRUG_LICENSEOperationCompleted = AddressOf Me.OnXML_DRUG_LICENSEOperationCompleted
            End If
            Me.InvokeAsync("XML_DRUG_LICENSE", New Object() {Newcode}, Me.XML_DRUG_LICENSEOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_DRUG_LICENSEOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_DRUG_LICENSECompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_DRUG_LICENSECompleted(Me, New XML_DRUG_LICENSECompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_GET_SEARCH_DRUG_DR_IOW_ESUB", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function XML_GET_SEARCH_DRUG_DR_IOW_ESUB(ByVal Newcode As String) As String
            Dim results() As Object = Me.Invoke("XML_GET_SEARCH_DRUG_DR_IOW_ESUB", New Object() {Newcode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XML_GET_SEARCH_DRUG_DR_IOW_ESUBAsync(ByVal Newcode As String)
            Me.XML_GET_SEARCH_DRUG_DR_IOW_ESUBAsync(Newcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_GET_SEARCH_DRUG_DR_IOW_ESUBAsync(ByVal Newcode As String, ByVal userState As Object)
            If (Me.XML_GET_SEARCH_DRUG_DR_IOW_ESUBOperationCompleted Is Nothing) Then
                Me.XML_GET_SEARCH_DRUG_DR_IOW_ESUBOperationCompleted = AddressOf Me.OnXML_GET_SEARCH_DRUG_DR_IOW_ESUBOperationCompleted
            End If
            Me.InvokeAsync("XML_GET_SEARCH_DRUG_DR_IOW_ESUB", New Object() {Newcode}, Me.XML_GET_SEARCH_DRUG_DR_IOW_ESUBOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_GET_SEARCH_DRUG_DR_IOW_ESUBOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompleted(Me, New XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_GET_SEARCH_DRUG_DR", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function XML_GET_SEARCH_DRUG_DR(ByVal Newcode As String) As String
            Dim results() As Object = Me.Invoke("XML_GET_SEARCH_DRUG_DR", New Object() {Newcode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XML_GET_SEARCH_DRUG_DRAsync(ByVal Newcode As String)
            Me.XML_GET_SEARCH_DRUG_DRAsync(Newcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_GET_SEARCH_DRUG_DRAsync(ByVal Newcode As String, ByVal userState As Object)
            If (Me.XML_GET_SEARCH_DRUG_DROperationCompleted Is Nothing) Then
                Me.XML_GET_SEARCH_DRUG_DROperationCompleted = AddressOf Me.OnXML_GET_SEARCH_DRUG_DROperationCompleted
            End If
            Me.InvokeAsync("XML_GET_SEARCH_DRUG_DR", New Object() {Newcode}, Me.XML_GET_SEARCH_DRUG_DROperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_GET_SEARCH_DRUG_DROperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_GET_SEARCH_DRUG_DRCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_GET_SEARCH_DRUG_DRCompleted(Me, New XML_GET_SEARCH_DRUG_DRCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/XML_GET_SEARCH_DRUG_LCN", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function XML_GET_SEARCH_DRUG_LCN(ByVal Newcode As String) As String
            Dim results() As Object = Me.Invoke("XML_GET_SEARCH_DRUG_LCN", New Object() {Newcode})
            Return CType(results(0),String)
        End Function
        
        '''<remarks/>
        Public Overloads Sub XML_GET_SEARCH_DRUG_LCNAsync(ByVal Newcode As String)
            Me.XML_GET_SEARCH_DRUG_LCNAsync(Newcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub XML_GET_SEARCH_DRUG_LCNAsync(ByVal Newcode As String, ByVal userState As Object)
            If (Me.XML_GET_SEARCH_DRUG_LCNOperationCompleted Is Nothing) Then
                Me.XML_GET_SEARCH_DRUG_LCNOperationCompleted = AddressOf Me.OnXML_GET_SEARCH_DRUG_LCNOperationCompleted
            End If
            Me.InvokeAsync("XML_GET_SEARCH_DRUG_LCN", New Object() {Newcode}, Me.XML_GET_SEARCH_DRUG_LCNOperationCompleted, userState)
        End Sub
        
        Private Sub OnXML_GET_SEARCH_DRUG_LCNOperationCompleted(ByVal arg As Object)
            If (Not (Me.XML_GET_SEARCH_DRUG_LCNCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent XML_GET_SEARCH_DRUG_LCNCompleted(Me, New XML_GET_SEARCH_DRUG_LCNCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/LOG_EDIT_TABEAN_HERB", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function LOG_EDIT_TABEAN_HERB(ByVal Newcode As String) As System.Data.DataTable
            Dim results() As Object = Me.Invoke("LOG_EDIT_TABEAN_HERB", New Object() {Newcode})
            Return CType(results(0),System.Data.DataTable)
        End Function
        
        '''<remarks/>
        Public Overloads Sub LOG_EDIT_TABEAN_HERBAsync(ByVal Newcode As String)
            Me.LOG_EDIT_TABEAN_HERBAsync(Newcode, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub LOG_EDIT_TABEAN_HERBAsync(ByVal Newcode As String, ByVal userState As Object)
            If (Me.LOG_EDIT_TABEAN_HERBOperationCompleted Is Nothing) Then
                Me.LOG_EDIT_TABEAN_HERBOperationCompleted = AddressOf Me.OnLOG_EDIT_TABEAN_HERBOperationCompleted
            End If
            Me.InvokeAsync("LOG_EDIT_TABEAN_HERB", New Object() {Newcode}, Me.LOG_EDIT_TABEAN_HERBOperationCompleted, userState)
        End Sub
        
        Private Sub OnLOG_EDIT_TABEAN_HERBOperationCompleted(ByVal arg As Object)
            If (Not (Me.LOG_EDIT_TABEAN_HERBCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent LOG_EDIT_TABEAN_HERBCompleted(Me, New LOG_EDIT_TABEAN_HERBCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_INSERT_LICENCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_INSERT_LICENCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_INSERT_LICENCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_INSERT_XML_LICEN_ALLCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_INSERT_XML_LICEN_ALLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_INSERT_XML_LICEN_ALLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_UPDATE_LICENCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_UPDATE_LICENCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_UPDATE_LICENCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_INSERT_DR15CompletedEventHandler(ByVal sender As Object, ByVal e As HERB_INSERT_DR15CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_INSERT_DR15CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_UPDATE_DH15CompletedEventHandler(ByVal sender As Object, ByVal e As HERB_UPDATE_DH15CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_UPDATE_DH15CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_INSERT_DR15_DEMOCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_INSERT_DR15_DEMOCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_INSERT_DR15_DEMOCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub UPDATE_TRANFERS_DRCompletedEventHandler(ByVal sender As Object, ByVal e As UPDATE_TRANFERS_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UPDATE_TRANFERS_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub UPDATE_SMP_DRCompletedEventHandler(ByVal sender As Object, ByVal e As UPDATE_SMP_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UPDATE_SMP_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_INSERT_DRCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_INSERT_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_INSERT_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub UPDATE_DR_HERB_FORCompletedEventHandler(ByVal sender As Object, ByVal e As UPDATE_DR_HERB_FORCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class UPDATE_DR_HERB_FORCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_UPDATE_DRCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_UPDATE_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_UPDATE_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_DELETE_DRCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_DELETE_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_DELETE_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_INSERT_XML_PRODUCT_ALLCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_INSERT_XML_PRODUCT_ALLCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_INSERT_XML_PRODUCT_ALLCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub HERB_UPDATE_XML_PRODUCTCompletedEventHandler(ByVal sender As Object, ByVal e As HERB_UPDATE_XML_PRODUCTCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class HERB_UPDATE_XML_PRODUCTCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XML_DRUG_BC_UPDATE_TBCompletedEventHandler(ByVal sender As Object, ByVal e As System.ComponentModel.AsyncCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XML_DRUG_FORMULACompletedEventHandler(ByVal sender As Object, ByVal e As XML_DRUG_FORMULACompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XML_DRUG_FORMULACompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XML_DRUG_LICENSECompletedEventHandler(ByVal sender As Object, ByVal e As XML_DRUG_LICENSECompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XML_DRUG_LICENSECompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompletedEventHandler(ByVal sender As Object, ByVal e As XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XML_GET_SEARCH_DRUG_DR_IOW_ESUBCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XML_GET_SEARCH_DRUG_DRCompletedEventHandler(ByVal sender As Object, ByVal e As XML_GET_SEARCH_DRUG_DRCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XML_GET_SEARCH_DRUG_DRCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub XML_GET_SEARCH_DRUG_LCNCompletedEventHandler(ByVal sender As Object, ByVal e As XML_GET_SEARCH_DRUG_LCNCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class XML_GET_SEARCH_DRUG_LCNCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As String
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),String)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")>  _
    Public Delegate Sub LOG_EDIT_TABEAN_HERBCompletedEventHandler(ByVal sender As Object, ByVal e As LOG_EDIT_TABEAN_HERBCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class LOG_EDIT_TABEAN_HERBCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As System.Data.DataTable
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),System.Data.DataTable)
            End Get
        End Property
    End Class
End Namespace
